/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swings;

/**
 *
 * @author anishgarg
 */
public class progress_bar extends javax.swing.JFrame {

    /**
     * Creates new form progress_bar
     */
    public progress_bar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        group2 = new javax.swing.ButtonGroup();
        group3 = new javax.swing.ButtonGroup();
        group4 = new javax.swing.ButtonGroup();
        gold = new javax.swing.JRadioButton();
        silver = new javax.swing.JRadioButton();
        bronze = new javax.swing.JRadioButton();
        porsche = new javax.swing.JRadioButton();
        mercedes = new javax.swing.JRadioButton();
        maseratti = new javax.swing.JRadioButton();
        salty = new javax.swing.JRadioButton();
        sweet = new javax.swing.JRadioButton();
        spicy = new javax.swing.JRadioButton();
        swimming = new javax.swing.JRadioButton();
        gym = new javax.swing.JRadioButton();
        music = new javax.swing.JRadioButton();
        progressbar = new javax.swing.JProgressBar();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        group1.add(gold);
        gold.setText("gold");
        gold.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group1.add(silver);
        silver.setText("silver");
        silver.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group1.add(bronze);
        bronze.setText("bronze");
        bronze.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group2.add(porsche);
        porsche.setText("porsche");
        porsche.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group2.add(mercedes);
        mercedes.setText("mercedes");
        mercedes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group2.add(maseratti);
        maseratti.setText("maseratti");
        maseratti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group3.add(salty);
        salty.setText("salty");
        salty.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group3.add(sweet);
        sweet.setText("sweet");
        sweet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group3.add(spicy);
        spicy.setText("spicy");
        spicy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group4.add(swimming);
        swimming.setText("swimming");
        swimming.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group4.add(gym);
        gym.setText("gym");
        gym.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        group4.add(music);
        music.setText("music");
        music.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });

        progressbar.setStringPainted(true);

        btn.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btn.setText("Reset");
        btn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                goldItemStateChanged(evt);
            }
        });
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bronze)
                                    .addComponent(silver)
                                    .addComponent(gold))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(porsche)
                                    .addComponent(maseratti)
                                    .addComponent(mercedes))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(salty)
                                    .addComponent(spicy)
                                    .addComponent(sweet))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(swimming)
                                    .addComponent(music)
                                    .addComponent(gym)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sweet)
                        .addGap(18, 18, 18)
                        .addComponent(spicy)
                        .addGap(26, 26, 26)
                        .addComponent(salty))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gym)
                        .addGap(18, 18, 18)
                        .addComponent(music)
                        .addGap(26, 26, 26)
                        .addComponent(swimming))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mercedes)
                        .addGap(18, 18, 18)
                        .addComponent(maseratti)
                        .addGap(26, 26, 26)
                        .addComponent(porsche))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gold)
                        .addGap(18, 18, 18)
                        .addComponent(silver)
                        .addGap(26, 26, 26)
                        .addComponent(bronze)))
                .addGap(39, 39, 39)
                .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        group1.clearSelection();
        group2.clearSelection();
        group3.clearSelection();
        group4.clearSelection();
        progressbar.setValue(0);
    }//GEN-LAST:event_btnActionPerformed

    private void goldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_goldItemStateChanged
        // TODO add your handling code here:
        int count=0;
        if(gold.isSelected() || silver.isSelected()|| bronze.isSelected())
        {
            count++;
        }
         if(mercedes.isSelected() || maseratti.isSelected()|| porsche.isSelected())
        {
            count++;
        }
          if(sweet.isSelected() || spicy.isSelected()|| salty.isSelected())
        {
            count++;
        }
           if(gym.isSelected() || music.isSelected()|| swimming.isSelected())
        {
            count++;
        }
           progressbar.setValue(count*25);
        
    }//GEN-LAST:event_goldItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(progress_bar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(progress_bar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(progress_bar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progress_bar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new progress_bar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bronze;
    private javax.swing.JButton btn;
    private javax.swing.JRadioButton gold;
    private javax.swing.ButtonGroup group1;
    private javax.swing.ButtonGroup group2;
    private javax.swing.ButtonGroup group3;
    private javax.swing.ButtonGroup group4;
    private javax.swing.JRadioButton gym;
    private javax.swing.JRadioButton maseratti;
    private javax.swing.JRadioButton mercedes;
    private javax.swing.JRadioButton music;
    private javax.swing.JRadioButton porsche;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JRadioButton salty;
    private javax.swing.JRadioButton silver;
    private javax.swing.JRadioButton spicy;
    private javax.swing.JRadioButton sweet;
    private javax.swing.JRadioButton swimming;
    // End of variables declaration//GEN-END:variables
}
